# Generated by Django 3.2.9 on 2022-01-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_forgotpasswordrequests_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpasswordrequests',
            name='token_hash',
            field=models.TextField(),
        ),
    ]
