# Generated by Django 3.2.9 on 2022-01-03 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPasswordRequests',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('token_hash', models.CharField(max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
